/* Generated by Edge Impulse
*
* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the "Software"), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in
* all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
* SOFTWARE.
*/

#ifndef _EI_CLASSIFIER_IMPULSE1_MODEL_METADATA_H_
#define _EI_CLASSIFIER_IMPULSE1_MODEL_METADATA_H_

#include <stdint.h>
#include "model_types.h"
#include "tflite-model/impulse1_model_compiled.h"
#include "edge-impulse-sdk/classifier/ei_run_dsp.h"

const char* impulse_1_categories[] = { "idle", "snake", "updown", "wave" };

ei_dsp_config_spectral_analysis_t impulse_1_dsp_config_458 = {
    1,
    3,
    1.00000f,
    "low",
    3.00000f,
    6,
    128,
    3,
    0.10000f,
    "0.1, 0.5, 1.0, 2.0, 5.0"
};

const size_t impulse_1_dsp_blocks_size = 1;
ei_model_dsp_t impulse_1_dsp_blocks[impulse_1_dsp_blocks_size] = {
    { // DSP block 458
        33,
        &extract_spectral_analysis_features,
        (void*)&impulse_1_dsp_config_458
    }
};

const size_t impulse_1_dsp_blocks_i16_size = 1;
ei_model_dsp_i16_t impulse_1_dsp_blocks_i16[impulse_1_dsp_blocks_i16_size] = {
    { // DSP block 458
        33,
        &extract_spectral_analysis_features,
        (void*)&impulse_1_dsp_config_458
    }
};

ei_impulse_t impulse_1 = {
    1, // uint32_t project_id;
    "EdgeImpulse Inc.", // const char *project_owner;
    "Continuous gestures", // const char *project_name;
    295, // int deploy_version;
    33, // uint32_t nn_input_frame_size;
    123, // uint32_t raw_sample_count;
    3, // uint32_t raw_samples_per_frame;
    (3 * 123), // uint32_t dsp_input_frame_size;
    0, // uint32_t input_width;
    0, // uint32_t input_height;
    16, // float interval_ms;
    4, // uint16_t label_count;
    0, // bool has_anomaly;
    62.5, // float frequency;
    false, // bool use_quantized_dsp_block;
    false, // bool object_detection;
    0, // uint16_t object_detection_count;
    0.5f, // float object_detection_threshold;
    1, // uint8_t tflite_output_labels_tensor;
    2, // uint8_t tflite_output_score_tensor;
    3673, // uint32_t tflite_arena_size;
    EI_CLASSIFIER_DATATYPE_INT8, // int tflite_input_datatype;
    1, // bool tflite_input_quantized;
    0.11557556688785553, // float tflite_input_scale;
    -128, // float tflite_input_zeropoint;
    EI_CLASSIFIER_DATATYPE_INT8, // int tflite_output_datatype;
    1, // bool tflite_output_quantized;
    0.00390625, // float tflite_output_scale;
    -128, // float tflite_output_zeropoint;
    EI_CLASSIFIER_TFLITE, // int inferencing_engine;
    true, // bool compiled;
    true, // bool has_tflite_ops_resolver;
    (123 / 4), // int sensor;
    4, // int slice_size;
    true, // int slices_per_model_window;
    impulse_1_categories, // const char **categories;
    &trained_model_1_input, // TfLiteTensor* (*model_input)(int);
    &trained_model_1_output, // TfLiteTensor* (*model_output)(int);
    &trained_model_1_init, // TfLiteStatus (*model_init)(void*(*alloc_fnc)(size_t,size_t));
    &trained_model_1_invoke, // TfLiteStatus (*model_invoke)();
    &trained_model_1_reset, // TfLiteStatus (*model_reset)(void (*free)(void* ptr));
    impulse_1_dsp_blocks_size, // size_t dsp_blocks_size;
    impulse_1_dsp_blocks, // ei_model_dsp_t **dsp_blocks;
    impulse_1_dsp_blocks_i16_size, // size_t dsp_i16_blocks_size;
    impulse_1_dsp_blocks_i16, // ei_model_dsp_i16_t **dsp_i16_blocks;
    nullptr, // uint8_t *tflite_file;
    0 // size_t tflite_file_size;
};

#endif // _EI_CLASSIFIER_IMPULSE1_MODEL_METADATA_H_
